import type { Metadata } from 'next';
import localFont from "next/font/local";
import '../globals.css';
import BottomNav from '@/components/shared/BottomNav';
import TopNav from '@/components/shared/TopNav';

export const metadata: Metadata = {
  title: 'Threads',
  description: 'Threads Clone Coding Project generated by create next app',
}


const pre = localFont({
  src: "../font/PretendardVariable.woff2",
  variable: "--pre",
  display:'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${pre.className} dark:bg-dark-bg bg-light-bg`}>
        <main>
          <TopNav />
            { children }
          <BottomNav />
        </main>
      </body>
    </html>
  )
}
