import type { Metadata } from 'next';
import localFont from "next/font/local";
import '../globals.css';
import BottomNav from '@/components/shared/BottomNav';
import TopNav from '@/components/shared/TopNav';
import { RecoilRoot } from 'recoil';
import Header from '@/components/shared/Header';

export const metadata: Metadata = {
  title: 'Threads',
  description: 'Threads Clone Coding Project generated by create next app',
}

const pre = localFont({
  src: "../font/PretendardVariable.woff2",
  variable: "--pre",
  display:'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-full'>
      <body className={`${pre.className} dark:bg-dark-bg bg-light-bg h-full`}>
        <main>
          <Header />
            <section className="mx-auto max-w-[620px] px-[24px] mobile:px-[15px] min-h-full mt-[20px]">{ children }</section>
          <BottomNav />
        </main>
      </body>
    </html>
  )
}
